### ISSUE TITLE
Not all the waveforms correctly downloaded

### ISSUE THREAD

**Issue by ZamirKhurshid** [alirezaniki/OBSTransformer#2]
When asking for BH* channels for a given number of earthquakes, the SAC saving option only downloads waveforms for the first channel (BH). For other channels, the message: "Sequence item 0: expected str instance, tuple found" appears. I have to select them one by one the channels, which is a real pain.
Can you explain what's going wrong.

**Comment by alirezaniki** [comment]
This is not an issue from OBSTransformer. I am not sure what code you are using, however, you may pass the channels as "BH?,HH?,EH?". That might help.

**Comment by ZamirKhurshid** [comment]
@alirezaniki Thanks for your response. I know that is not related to OBSTransformer. I am curious about data from where I download waveform data. I have tried with IRIS from obspy but it shows no data is available. Please share waveform data or proper link of data.

**Comment by alirezaniki** [comment]
The data used to train the OBSTransformer model will be uploaded here after the paper got accepted. If the code says there is no data, whether there is no recording within the given time range or there is something wrong with the parameter settings.

**Comment by ZamirKhurshid** [comment]
Well noted. I am giving info like this, Channel "BHZ*", Network "YM*",  Station"01,02" Starttime "2016" end time "2017 with dtaes" but it show no data found along these parameters.

**Comment by alirezaniki** [comment]
The channel seems incorrect to me. It could be "BH?" if you know the network's channels are BHZ, BH1, and BH2. If you are not sure, pass multiple channels like "BH?, HH?, EH?". You better share the code here so that I can assist better.

**Comment by ZamirKhurshid** [comment]
Please have a look at this code. And let me know where I am making mistakes.
